/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.greencode.maquina.gui;

import com.greencode.coleta.arduino.ColetaArduino;
import com.greencode.maquina.Application;
import com.greencode.maquina.model.Reciclavel;
import com.greencode.maquina.model.Usuario;
import com.greencode.maquina.service.Services;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author lucas
 */
public class Reciclando extends javax.swing.JFrame {

    static Application ex;
    int valor = 0;
    ColetaArduino arduino = new ColetaArduino();
    Usuario user;
    Reciclavel reciclavel = new Reciclavel(1L, 2, 20, 1);
    ImageIcon reciclandoIcon = new ImageIcon("src/main/java/com/greencode/icons/fundo-recliando-1.png");
    ImageIcon reciclarIcon = new ImageIcon("src/main/java/com/greencode/icons/btn-reciclar.png");
    ImageIcon terminarIcon = new ImageIcon("src/main/java/com/greencode/icons/btn-terminar.png");
    
    @Autowired
    Services services = new Services();
    
    boolean bool = true;

    /**
     * Creates new form Reciclando
     */
    public Reciclando() {
        initComponents();
        reciclandoIcon.setImage(reciclandoIcon.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), 1));
        jLabel1.setIcon(reciclandoIcon);
        reciclarIcon.setImage(reciclarIcon.getImage().getScaledInstance(btnReciclar.getWidth(), btnReciclar.getHeight(), 1));
        btnReciclar.setIcon(reciclarIcon);
        terminarIcon.setImage(terminarIcon.getImage().getScaledInstance(btnTerminar.getWidth(), btnTerminar.getHeight(), 1));
        btnTerminar.setIcon(terminarIcon);
    }

    Thread contagem = new Thread() {

        boolean wait = false;

        @Override
        public void run() {
            while (bool) {
                wait = !wait;
                if (arduino.CapturaDados(wait)) {
                    totalReciclando.setText(String.valueOf(++valor));
                }
            }
        }
    };

    public void recebeAnterior(Application app, Usuario usuario) {
        ex = app;
        user = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        totalReciclando = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JLabel();
        btnReciclar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bemVindo = new javax.swing.JLabel();
        textoReciclando = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(635, 440));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(635, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 3, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(640, 480));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 48));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 87, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Reciclando atualmente");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 285, -1));

        totalReciclando.setFont(new java.awt.Font("Ubuntu", 1, 150)); // NOI18N
        totalReciclando.setForeground(new java.awt.Color(254, 254, 254));
        totalReciclando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalReciclando.setText("0");
        jPanel4.add(totalReciclando, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 285, 160));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 160, 285, 200));

        btnTerminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTerminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTerminarMouseClicked(evt);
            }
        });
        jPanel1.add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 390, 285, 45));

        btnReciclar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReciclar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReciclarMouseClicked(evt);
            }
        });
        jPanel1.add(btnReciclar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 290, 45));

        jPanel3.setBackground(new java.awt.Color(151, 205, 41));
        jPanel3.setBorder(null);
        jPanel3.setForeground(new java.awt.Color(254, 254, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Total Reciclado");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 15, 285, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("0");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 51, 285, 32));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 285, 95));

        jPanel2.setBackground(new java.awt.Color(5, 108, 84));
        jPanel2.setBorder(null);
        jPanel2.setForeground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("0");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 51, 285, 30));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 254, 254));
        jLabel7.setText("Seus Pontos");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 15, 285, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, 285, 95));

        bemVindo.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        bemVindo.setForeground(new java.awt.Color(254, 254, 254));
        bemVindo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(bemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 640, 50));

        textoReciclando.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        textoReciclando.setForeground(new java.awt.Color(254, 254, 254));
        textoReciclando.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(textoReciclando, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 640, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReciclarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReciclarMouseClicked
        textoReciclando.setText("Você está reciclando...");
        bool = true;
        if(!contagem.isAlive()){
            contagem.start();
        }
    }//GEN-LAST:event_btnReciclarMouseClicked

    private void btnTerminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTerminarMouseClicked
        int novoPonto = user.getPontos() + (valor * reciclavel.getPontos());
        int novoQtdItens = user.getTotalItens() + valor;
        services.atualizarPontos(user, novoPonto);
        services.atualizarItens(user, novoQtdItens);
        
    	bool = false;
        ex.recebeAnterior(this);
        ex.setVisible(true);
        setVisible(false);
        textoReciclando.setText("");
        ex.resetUsername();
        ex.resetPassField();
        totalReciclando.setText("0");
        valor = 0;
        bemVindo.setText("");
    }//GEN-LAST:event_btnTerminarMouseClicked

    public void setBemVindo(String nome){
        bemVindo.setText("Bem Vindo " + nome);
        
    }
    
    public void setDados(Usuario user) {
    	jLabel6.setText(user.getPontos()+"");
    	jLabel11.setText(user.getTotalItens()+"");
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bemVindo;
    private javax.swing.JLabel btnReciclar;
    private javax.swing.JLabel btnTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel textoReciclando;
    private javax.swing.JLabel totalReciclando;
    // End of variables declaration//GEN-END:variables
}